services:
  backend:
    build:
      context: ./backend
    container_name: codequest-backend
    ports:
      - "5000:5000"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: http://65.0.168.61:5000
    container_name: codequest-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped